### ISSUE TITLE
Rework PV ground detail settings

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#30]
As mentioned before, we need a new layout for the PV ground, draft see below. 3 boxes (different shades of yellow as in the DP app, same color as the polygons on the map) or sth similar which is visually in line with the other detail settings..
The icons are the new ones you're currently working on.

![image](https://github.com/empowerplan/epp-app/assets/15910173/c36e5051-83cc-4496-8e20-977b00044f54)

**Comment by bmlancien** [comment]
Something like this? The labels are quite long. Not sure if there is a way to improve this.

![Einstellungen_FF_PV](https://github.com/empowerplan/epp-app/assets/33999424/44b734c3-73c3-474f-9052-983715ed9bd1)

I would rather stick to the same slider blue, even on the settings details panel, because it's getting messy with so many colors.

![Einstellungen_FF_PV_colors](https://github.com/empowerplan/epp-app/assets/33999424/547756ec-bf98-4b91-a4d0-fcd029fa49eb)

**Comment by nesnoj** [comment]
Thx for the draft! Please implement. Some notes:
- Please keep the 2nd color version as it is the visual connection to the layers shown in the map
- Icons: good, but please use the classical icon ![image](https://github.com/empowerplan/epp-app/assets/15910173/e9526d10-0745-43e2-a1ad-62ea0a582024) for the first entry
- Keep the long text for now, I'll shorten them after implementation.
