### ISSUE TITLE
Layout for non-ready charts

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#95]
In #82 pre-results are being integrated.
The result charts whose data depend on the simulation results must be styled to indicate this, cf. https://github.com/empowerplan/epp-app/issues/60#issuecomment-2042282852 . As soon as the simulation finishes, results are loaded and design switches to "normal".

Could you come up with a proposal @bmlancien ?

**Comment by bmlancien** [comment]
In any case, the quick-to-calculate results should be visible first. 

1. We could display the detailed results below them with first a loading indicator (percentage and/or time left) and an explanation text. The question is if all the buttons on the sidebar should be clickable or not during calculation.

![Results_overview_loading_1](https://github.com/empowerplan/epp-app/assets/33999424/7aaa9565-4ca6-433b-b02f-8496313c3b75)

2. Instead of an explanation text, a series of fun facts about the topic:

![Results_overview_loading_2](https://github.com/empowerplan/epp-app/assets/33999424/075ddc70-5d60-462d-ac95-ed1358971dc0)

3. We could also decide to use the sidebar to give a feedback to the users that more results are to come. For example using a skeleton to show that more elements are coming (in that case buttons about technologies and sectors, or whatever we think makes sense). These element will be displayed and clickable once the results are ready.

![skeleton](https://github.com/empowerplan/epp-app/assets/33999424/aed10bb3-cb6c-4cb2-b241-4665439eb840)

We should also think about error handling:

![Results_overview_error](https://github.com/empowerplan/epp-app/assets/33999424/856122fb-cb96-4580-897c-11013f29a460)

**Comment by nesnoj** [comment]
Very nice proposals! :smile: 
- I prefer to use the sidebar as it is always visible and there's enough space left. Currently (as implemented in #82) it looks like this (in the map results though): 
![image](https://github.com/empowerplan/epp-app/assets/15910173/404200be-8443-4b62-9136-7b5fd4903c49)
The new progress bar should be visible in both sidebars: map and charts (at the very top).
- I like the kind of explanation why it takes some time. However, we don't have too much space in the sidebar, so a button "Warum ...?" which shows the textblock "Es werden komplexe..." might be more suitable
- The blinking elements for results to come are not necessary for the left categories, but we need sth. like this for the charts
- I like the idea of fun facts but as the user can already go into the pre-results it'd be rather distracting?!
- The error message is a good idea too!
- I propose two timeouts set in cfg: 1) usual calculation time (1 min), 2) error time (2 min) -> this would allow some more time for the calc (in case of heavy server load) but indicating typical calc. time.

@henhuy Any objections?

**Comment by henhuy** [comment]
Your suggestions look nice - thank you @bmlancien !

I also like the blinking skeleton. Maybe we could do something similar in the dropdown, if there are some results which cannot be pre-calculated.

I'm not a big fan of those fun facts, though - but that's up to you. :)

Error message is a good idea!

Considering the progress bar:
As you already proposed @nesnoj  - we cannot give out a "real" calculation time, but instead have to go with typical once and can only fake progression. Faking percentages seems werid for me though. Maybe instead only three steps? Or just an indicator if its taking longer than usual.. Don't know.

**Comment by bmlancien** [comment]
Alright, thanks for the feedback. Here are some new designs from Figma. 

- I moved the content to the sidebar at the top. It should be the same on map or charts view. 
- The loading and error messages could be visible on a tooltip. As an alternative we could also turn this as a modal.
- Skeletons for charts that aren't calculated yet

![Results_overview_loading](https://github.com/empowerplan/epp-app/assets/33999424/176a2ae8-d2e8-4d5a-bfcd-52c83ce33fe3)

![Results_overview_loading_hover](https://github.com/empowerplan/epp-app/assets/33999424/2742f20b-e6f2-4fd6-9ad6-2e567c970498)

![Results_overview_error](https://github.com/empowerplan/epp-app/assets/33999424/46535fee-391b-41da-9125-237ac49e772f)

![Results_overview_error_hover](https://github.com/empowerplan/epp-app/assets/33999424/a02726d1-5f85-4d23-88bd-7c66c1469c99)
